{% set name = "DENTIST" %}
{% set git_url = environ.get("GIT_URL", "https://github.com/a-ludi/dentist.git") %}
{% set git_rev = environ.get("DENTIST_VERSION", "v4.0.0") %}

{% set version = environ['GIT_DESCRIBE_TAG'] %}
{% if version[0] == "v" %}
  {% set version = version[1:] %}
{% endif %}
{% if git_rev[0] != "v" %}
  {% set version = "local" %}
{% endif %}
{% if environ['GIT_DESCRIBE_NUMBER'] == 0 %}
  {% set version = version~".dev"~environ['GIT_BUILD_STR'] %}
{% endif %}

{% set build_type = environ.get('BUILD_TYPE', 'release') %}
{% set version_dub = version %}
{% set build_config = environ.get('DUB_CONFIG', 'default') %}
{% if build_type != "release" %}
  {% set version_dub = version_dub~"."~build_type %}
{% endif %}
{% if build_config != "default" %}
  {% set version_dub = version_dub~"."~build_config %}
{% endif %}

package:
  name:     "{{ name | lower }}"
  version:  "{{ version }}"

source:
  git_rev: "{{ git_rev }}"
  git_url: https://github.com/a-ludi/dentist.git

requirements:
  run:
    - dentist-core=={{ version_dub }}
    - dentist-workflow=={{ version }}

test:
  source_files:
    - tests/test-commands.sh
    - tests/test-workflow.sh
  commands:
    - "dentist -d"
    - "tests/test-commands.sh"
    - "tests/test-workflow.sh"

about:
  home: https://a-ludi.github.io/dentist/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DENTIST uses long reads to close assembly gaps at high accuracy.
  tags:
    - gap-filling
    - close-assembly-gaps
    - bioinformatics
    - genome-assembly
    - pacbio
    - long-reads
    - cluster
